version: "3.9"

services:
  api:
    build: .
    container_name: backend-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"