services:
  api:
    build: .
    container_name: movie-hub
    command: sh -c "npx prisma migrate deploy && npm start"
    ports:
      - "5000:3000"
    depends_on:
      - redis
    env_file:
      - .env.docker

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"

  postgres:
    image: postgres:15
    container_name: postgres
    env_file:
      - .env.docker
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
